### ISSUE TITLE
Basic formatting for news items

### ISSUE THREAD

**Issue by sebix** [SK-CERT/Taranis-NG#16] opened 2021-11-01 22:36 UTC
Even though rendering HTML tags can be a risk, IMHO we can and should render some of them - paragraphs, newlines, basic inline formatting (bold/italic/...) and links to improve readability. Currently all text is just shown as one long string without any formatting, e.g.:
![image](https://user-images.githubusercontent.com/199050/139750979-384a3f8f-4988-4201-a48d-485a8f0089d5.png)

**Comment by milankowww** [comment] 2021-11-15 15:14
closing as duplicate of #8 .

**Closed by milankowww** 2021-11-15 15:14 UTC
Labels: enhancement
